version: '2'
services:
    littlegreenmen-app:
        image: littlegreenmen
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://littlegreenmen-postgresql:5432/LittleGreenMen
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    littlegreenmen-postgresql:
        extends:
            file: postgresql.yml
            service: littlegreenmen-postgresql
